/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secondhandcars.ui.gui;

import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import secondhandcars.application.IController;
import secondhandcars.domain.Car;

/**
 *
 * @author Kristian
 */
public class CarWindow extends javax.swing.JFrame {
    IController ctr;
    Object [][] tableDate = {
        {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
    };
    String[] tableColumnName = {
        "Year", "Mark", "Model", "Version", "Volume of engine", "Fuel", "Odometer", "Price of purchase", "Selling price", "Type", "Description", "License plate", "Date of purchase", "In stock"
    };
    DefaultTableModel dtm = new DefaultTableModel(tableDate, tableColumnName);
    
    public CarWindow(IController ctr) {
        this.ctr = ctr;
        initComponents();
        MainFrame.setModel(dtm);
        MainFrame.getColumnModel().getColumn(0).setPreferredWidth(70);
        MainFrame.getColumnModel().getColumn(1).setPreferredWidth(90);
        MainFrame.getColumnModel().getColumn(2).setPreferredWidth(90);
        MainFrame.getColumnModel().getColumn(3).setPreferredWidth(90);
        MainFrame.getColumnModel().getColumn(4).setPreferredWidth(110);
        MainFrame.getColumnModel().getColumn(5).setPreferredWidth(90);
        MainFrame.getColumnModel().getColumn(6).setPreferredWidth(70);
        MainFrame.getColumnModel().getColumn(7).setPreferredWidth(110);
        MainFrame.getColumnModel().getColumn(8).setPreferredWidth(90);
        MainFrame.getColumnModel().getColumn(9).setPreferredWidth(90);
        MainFrame.getColumnModel().getColumn(10).setPreferredWidth(110);
        MainFrame.getColumnModel().getColumn(11).setPreferredWidth(90);
        MainFrame.getColumnModel().getColumn(12).setPreferredWidth(110);
        MainFrame.getColumnModel().getColumn(13).setPreferredWidth(60);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAllCars = new javax.swing.JButton();
        infoText = new javax.swing.JTextField();
        btnSeachCar = new javax.swing.JButton();
        btnViewAllSoldCars = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MainFrame = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAllCars.setText("View all available cars");
        btnAllCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllCarsActionPerformed(evt);
            }
        });

        infoText.setEnabled(false);

        btnSeachCar.setText("Search cars");
        btnSeachCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachCarActionPerformed(evt);
            }
        });

        btnViewAllSoldCars.setText("Sold cars");
        btnViewAllSoldCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllSoldCarsActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        MainFrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Year", "Mark", "Model", "Version", "Volume of engine", "Fuel", "Odometer", "Price of purchase", "Selling price", "Type", "Description", "License plate", "Date of purchase", "In stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MainFrame.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(MainFrame);
        if (MainFrame.getColumnModel().getColumnCount() > 0) {
            MainFrame.getColumnModel().getColumn(0).setPreferredWidth(70);
            MainFrame.getColumnModel().getColumn(1).setPreferredWidth(90);
            MainFrame.getColumnModel().getColumn(2).setPreferredWidth(90);
            MainFrame.getColumnModel().getColumn(3).setPreferredWidth(90);
            MainFrame.getColumnModel().getColumn(4).setPreferredWidth(130);
            MainFrame.getColumnModel().getColumn(5).setPreferredWidth(90);
            MainFrame.getColumnModel().getColumn(6).setPreferredWidth(70);
            MainFrame.getColumnModel().getColumn(7).setPreferredWidth(130);
            MainFrame.getColumnModel().getColumn(8).setPreferredWidth(90);
            MainFrame.getColumnModel().getColumn(9).setPreferredWidth(90);
            MainFrame.getColumnModel().getColumn(10).setPreferredWidth(110);
            MainFrame.getColumnModel().getColumn(11).setPreferredWidth(90);
            MainFrame.getColumnModel().getColumn(12).setPreferredWidth(110);
            MainFrame.getColumnModel().getColumn(13).setPreferredWidth(60);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoText)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAllCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSeachCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewAllSoldCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAllCars)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSeachCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewAllSoldCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeachCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachCarActionPerformed
        JFrame searchMenu = new SearchASpecificCar(ctr, this);
        
        searchMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        searchMenu.setResizable(false);
        searchMenu.setTitle("Search Cars Menu");
        searchMenu.setVisible(true);
        searchMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSeachCarActionPerformed

    private void btnViewAllSoldCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllSoldCarsActionPerformed
        JFrame soldCars = new SoldCars(ctr, this);
        
        soldCars.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        soldCars.setResizable(false);
        soldCars.setTitle("Sold Cars Menu");
        soldCars.setVisible(true);
        soldCars.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnViewAllSoldCarsActionPerformed

    private void btnAllCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllCarsActionPerformed
        List<Car> cars = ctr.getAllCars();
        displayCars(cars);
    }//GEN-LAST:event_btnAllCarsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainMenu mainMenu = new MainMenu(ctr);
        
        mainMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mainMenu.setResizable(false);
        mainMenu.setTitle("Sold Cars Menu");
        mainMenu.setVisible(true);
        mainMenu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * Takes a list of car and display them on the table.
     * @param cars - List of cars to be displayed
     */
    public void displayCars(List<Car> cars) {
        if (dtm.getRowCount() > 0) {
            for (int i = dtm.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
        }
        for (Car car : cars) {
            Object[] data = new Object[14];
            data[0] = car.getYear();
            data[1] = car.getMark();
            data[2] = car.getModel();
            data[3] = car.getVersion();
            data[4] = car.getVolumeOfEngine();
            data[5] = car.getFuelType();
            data[6] = car.getOdometer();
            data[7] = car.getPriceOfPurchase();
            data[8] = car.getSellingPrice();
            data[9] = car.getType();
            data[10] = car.getDescription();
            data[11] = car.getLicensePlate();
            data[12] = car.getDateOfPurchase();
            data[13] = car.getStockStatus();
            dtm.addRow(data);
        }
    }
    
    public void setInfoText(String text, boolean error) {
        if (error) {
            infoText.setDisabledTextColor(Color.red);
            infoText.setText(text);
        }
        else {
            infoText.setDisabledTextColor(Color.black);
            infoText.setText(text);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MainFrame;
    private javax.swing.JButton btnAllCars;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSeachCar;
    private javax.swing.JButton btnViewAllSoldCars;
    private javax.swing.JTextField infoText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
