/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secondhandcars.ui.gui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import secondhandcars.application.IController;
import secondhandcars.domain.Car;

/**
 *
 * @author Cornel
 */
public class Sales extends javax.swing.JFrame {
    IController ctr;

    /**
     * Creates new form Sales
     * @param ctr
     */
    public Sales(IController ctr) {
        this.ctr = ctr;
        initComponents();
        removeGetCarsPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCreateReportOfTransactions = new javax.swing.JButton();
        btnCreateReportBetweenDates = new javax.swing.JButton();
        panelGetCars = new javax.swing.JPanel();
        labelFromDate = new javax.swing.JLabel();
        labelToTheDate = new javax.swing.JLabel();
        fieldStartYear = new javax.swing.JTextField();
        fieldStartMonth = new javax.swing.JTextField();
        fieldStartDay = new javax.swing.JTextField();
        dayOfPurchaseLabel = new javax.swing.JLabel();
        monthOfPurchaseLabel = new javax.swing.JLabel();
        yearOfPurchaseLabel = new javax.swing.JLabel();
        fieldEndYear = new javax.swing.JTextField();
        fieldEndMonth = new javax.swing.JTextField();
        fieldEndDay = new javax.swing.JTextField();
        dayOfPurchaseLabel1 = new javax.swing.JLabel();
        monthOfPurchaseLabel1 = new javax.swing.JLabel();
        yearOfPurchaseLabel1 = new javax.swing.JLabel();
        btnCreateReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(445, 345));

        btnCreateReportOfTransactions.setText("Create report");
        btnCreateReportOfTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateReportOfTransactionsActionPerformed(evt);
            }
        });

        btnCreateReportBetweenDates.setText("Create report between dates");
        btnCreateReportBetweenDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateReportBetweenDatesActionPerformed(evt);
            }
        });

        labelFromDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelFromDate.setText("From Date");

        labelToTheDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelToTheDate.setText("To Date");

        dayOfPurchaseLabel.setText("day");
        dayOfPurchaseLabel.setToolTipText("");

        monthOfPurchaseLabel.setText("month");
        monthOfPurchaseLabel.setToolTipText("");

        yearOfPurchaseLabel.setText("year");
        yearOfPurchaseLabel.setToolTipText("");

        dayOfPurchaseLabel1.setText("day");
        dayOfPurchaseLabel1.setToolTipText("");

        monthOfPurchaseLabel1.setText("month");
        monthOfPurchaseLabel1.setToolTipText("");

        yearOfPurchaseLabel1.setText("year");
        yearOfPurchaseLabel1.setToolTipText("");

        btnCreateReport.setText("Create");
        btnCreateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGetCarsLayout = new javax.swing.GroupLayout(panelGetCars);
        panelGetCars.setLayout(panelGetCarsLayout);
        panelGetCarsLayout.setHorizontalGroup(
            panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetCarsLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGetCarsLayout.createSequentialGroup()
                        .addComponent(fieldEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(panelGetCarsLayout.createSequentialGroup()
                        .addComponent(fieldStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(panelGetCarsLayout.createSequentialGroup()
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGetCarsLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGetCarsLayout.createSequentialGroup()
                                .addComponent(dayOfPurchaseLabel)
                                .addGap(43, 43, 43)
                                .addComponent(monthOfPurchaseLabel)
                                .addGap(34, 34, 34)
                                .addComponent(yearOfPurchaseLabel))
                            .addGroup(panelGetCarsLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(dayOfPurchaseLabel1)
                                .addGap(20, 20, 20)
                                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelToTheDate)
                                    .addGroup(panelGetCarsLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(monthOfPurchaseLabel1)
                                        .addGap(41, 41, 41)
                                        .addComponent(yearOfPurchaseLabel1))))))
                    .addGroup(panelGetCarsLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(labelFromDate))
                    .addComponent(btnCreateReport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGetCarsLayout.setVerticalGroup(
            panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetCarsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFromDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayOfPurchaseLabel)
                    .addComponent(monthOfPurchaseLabel)
                    .addComponent(yearOfPurchaseLabel))
                .addGap(9, 9, 9)
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelToTheDate)
                .addGap(7, 7, 7)
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthOfPurchaseLabel1)
                    .addComponent(yearOfPurchaseLabel1)
                    .addComponent(dayOfPurchaseLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnCreateReport))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGetCars, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCreateReportOfTransactions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateReportBetweenDates)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateReportOfTransactions)
                    .addComponent(btnCreateReportBetweenDates))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGetCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateReportBetweenDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateReportBetweenDatesActionPerformed
        panelGetCars.setVisible(true);
    }//GEN-LAST:event_btnCreateReportBetweenDatesActionPerformed

    private void btnCreateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateReportActionPerformed
        //Creates the date
        int sD = ctr.stringToInt(fieldStartDay.getText());                                       
        int sM = ctr.stringToInt(fieldStartMonth.getText());                                       
        int sY = ctr.stringToInt(fieldStartYear.getText());
        int eD = ctr.stringToInt(fieldEndDay.getText());                                       
        int eM = ctr.stringToInt(fieldEndMonth.getText());                                       
        int eY = ctr.stringToInt(fieldEndYear.getText());
        
  
    }//GEN-LAST:event_btnCreateReportActionPerformed

    private void btnCreateReportOfTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateReportOfTransactionsActionPerformed
        
    }//GEN-LAST:event_btnCreateReportOfTransactionsActionPerformed

    private void removeGetCarsPanel(){
        panelGetCars.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateReport;
    private javax.swing.JButton btnCreateReportBetweenDates;
    private javax.swing.JButton btnCreateReportOfTransactions;
    private javax.swing.JLabel dayOfPurchaseLabel;
    private javax.swing.JLabel dayOfPurchaseLabel1;
    private javax.swing.JTextField fieldEndDay;
    private javax.swing.JTextField fieldEndMonth;
    private javax.swing.JTextField fieldEndYear;
    private javax.swing.JTextField fieldStartDay;
    private javax.swing.JTextField fieldStartMonth;
    private javax.swing.JTextField fieldStartYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFromDate;
    private javax.swing.JLabel labelToTheDate;
    private javax.swing.JLabel monthOfPurchaseLabel;
    private javax.swing.JLabel monthOfPurchaseLabel1;
    private javax.swing.JPanel panelGetCars;
    private javax.swing.JLabel yearOfPurchaseLabel;
    private javax.swing.JLabel yearOfPurchaseLabel1;
    // End of variables declaration//GEN-END:variables
}
