/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secondhandcars.ui.gui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import secondhandcars.application.IController;
import secondhandcars.domain.Car;

/**
 *
 * @author Cornel
 */
public class ServiceWindow extends javax.swing.JFrame {
    //CarWindow carWindow;
    IController ctr;

    /**
     * Creates new form SoldCars
     */
    public ServiceWindow(IController ctr) {
        this.ctr = ctr;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        servicePanel = new javax.swing.JPanel();
        btnRepair = new javax.swing.JButton();
        btnChipTuning = new javax.swing.JButton();
        panelGetCars = new javax.swing.JPanel();
        labelFromDate = new javax.swing.JLabel();
        labelToTheDate = new javax.swing.JLabel();
        btnSearchGetCars = new javax.swing.JButton();
        fieldStartYear = new javax.swing.JTextField();
        fieldStartMonth = new javax.swing.JTextField();
        fieldStartDay = new javax.swing.JTextField();
        dayFromLabel = new javax.swing.JLabel();
        monthFromLabel = new javax.swing.JLabel();
        yearOfPurchaseLabel = new javax.swing.JLabel();
        fieldEndYear = new javax.swing.JTextField();
        fieldEndMonth = new javax.swing.JTextField();
        fieldEndDay = new javax.swing.JTextField();
        dayOfEndingLabel = new javax.swing.JLabel();
        monthOfEndingLabel = new javax.swing.JLabel();
        yearOfPurchaseLabel1 = new javax.swing.JLabel();
        btnTireHotel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRepair.setText("Repair");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });

        btnChipTuning.setText("Chip tuning");
        btnChipTuning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChipTuningActionPerformed(evt);
            }
        });

        labelFromDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelFromDate.setText("From Date");

        labelToTheDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelToTheDate.setText("To Date");
        labelToTheDate.setEnabled(false);

        btnSearchGetCars.setText("Commit");
        btnSearchGetCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGetCarsActionPerformed(evt);
            }
        });

        dayFromLabel.setText("day");
        dayFromLabel.setToolTipText("");

        monthFromLabel.setText("month");
        monthFromLabel.setToolTipText("");

        yearOfPurchaseLabel.setText("year");
        yearOfPurchaseLabel.setToolTipText("");

        fieldEndYear.setEnabled(false);

        fieldEndMonth.setEnabled(false);

        fieldEndDay.setEnabled(false);

        dayOfEndingLabel.setText("day");
        dayOfEndingLabel.setToolTipText("");
        dayOfEndingLabel.setEnabled(false);

        monthOfEndingLabel.setText("month");
        monthOfEndingLabel.setToolTipText("");
        monthOfEndingLabel.setEnabled(false);

        yearOfPurchaseLabel1.setText("year");
        yearOfPurchaseLabel1.setToolTipText("");
        yearOfPurchaseLabel1.setEnabled(false);

        javax.swing.GroupLayout panelGetCarsLayout = new javax.swing.GroupLayout(panelGetCars);
        panelGetCars.setLayout(panelGetCarsLayout);
        panelGetCarsLayout.setHorizontalGroup(
            panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetCarsLayout.createSequentialGroup()
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGetCarsLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGetCarsLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelGetCarsLayout.createSequentialGroup()
                                        .addComponent(dayFromLabel)
                                        .addGap(43, 43, 43)
                                        .addComponent(monthFromLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(yearOfPurchaseLabel))
                                    .addGroup(panelGetCarsLayout.createSequentialGroup()
                                        .addComponent(dayOfEndingLabel)
                                        .addGap(43, 43, 43)
                                        .addComponent(monthOfEndingLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(yearOfPurchaseLabel1)))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGetCarsLayout.createSequentialGroup()
                                .addComponent(fieldStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(fieldStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGetCarsLayout.createSequentialGroup()
                                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelGetCarsLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(labelToTheDate))
                                    .addGroup(panelGetCarsLayout.createSequentialGroup()
                                        .addComponent(fieldEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                        .addComponent(fieldEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(fieldEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelGetCarsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearchGetCars)))
                .addGap(96, 96, 96))
            .addGroup(panelGetCarsLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(labelFromDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGetCarsLayout.setVerticalGroup(
            panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGetCarsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFromDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayFromLabel)
                    .addComponent(monthFromLabel)
                    .addComponent(yearOfPurchaseLabel))
                .addGap(1, 1, 1)
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(labelToTheDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayOfEndingLabel)
                    .addComponent(monthOfEndingLabel)
                    .addComponent(yearOfPurchaseLabel1))
                .addGap(1, 1, 1)
                .addGroup(panelGetCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnSearchGetCars))
        );

        btnTireHotel.setText("Tire Hotel");
        btnTireHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTireHotelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout servicePanelLayout = new javax.swing.GroupLayout(servicePanel);
        servicePanel.setLayout(servicePanelLayout);
        servicePanelLayout.setHorizontalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(servicePanelLayout.createSequentialGroup()
                        .addComponent(btnRepair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChipTuning, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTireHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelGetCars, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        servicePanelLayout.setVerticalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRepair)
                    .addComponent(btnChipTuning)
                    .addComponent(btnTireHotel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGetCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(servicePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(servicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChipTuningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChipTuningActionPerformed
        panelGetCars.setVisible(true);
    }//GEN-LAST:event_btnChipTuningActionPerformed

    private void btnSearchGetCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGetCarsActionPerformed
        //Creates the date
        int sD = ctr.stringToInt(fieldStartDay.getText());                                       
        int sM = ctr.stringToInt(fieldStartMonth.getText());                                       
        int sY = ctr.stringToInt(fieldStartYear.getText());
        int eD = ctr.stringToInt(fieldEndDay.getText());                                       
        int eM = ctr.stringToInt(fieldEndMonth.getText());                                       
        int eY = ctr.stringToInt(fieldEndYear.getText());
        Date startDate;
        Date endDate;
        if (sD < 0 || sM < 0 || sY < 0 || eD < 0 || eM < 0 || eY < 0) {
            startDate = null;                       //If one or more fields of the date are empty.
            endDate = null;
        }
        else {
            startDate = createDate(sD, sM, sY);     //Creates the dates if fields were filled.
            endDate = createDate(eD, eM, eY);
        }
        if (startDate != null) {
            List<Car> cars = ctr.getSoldCarsBetweenDate(startDate, endDate);
            //carWindow.displayCars(cars);
        }
        else
            //carWindow.setInfoText("Invalid date!", true);
        this.dispose();
    }//GEN-LAST:event_btnSearchGetCarsActionPerformed

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        
        
    }//GEN-LAST:event_btnRepairActionPerformed

    private void btnTireHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTireHotelActionPerformed
        labelToTheDate.setEnabled(true);
        dayOfEndingLabel.setEnabled(true);
        monthOfEndingLabel.setEnabled(true);
        yearOfPurchaseLabel1.setEnabled(true);
        fieldEndDay.setEnabled(true);
        fieldEndMonth.setEnabled(true);
        fieldEndYear.setEnabled(true);
    }//GEN-LAST:event_btnTireHotelActionPerformed

    /**
     * Creates a date from an integer day, month and year.
     * @param d - the day to be parsed
     * @param m - the month to be parsed
     * @param y - the year to be parsed
     * @return the date
     */
    private Date createDate(int d, int m, int y) {
        String sD = (d < 10) ? "0" + d: "" + d;
        String sM = (m < 10) ? "0" + m: "" + m;
        try {
            return new SimpleDateFormat("dd-MM-yyyy").parse(sD + "-" + sM + "-" + y);
        } catch (ParseException ex) {
            ex.getMessage();
        }
        return null;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChipTuning;
    private javax.swing.JButton btnRepair;
    private javax.swing.JButton btnSearchGetCars;
    private javax.swing.JButton btnTireHotel;
    private javax.swing.JLabel dayFromLabel;
    private javax.swing.JLabel dayOfEndingLabel;
    private javax.swing.JTextField fieldEndDay;
    private javax.swing.JTextField fieldEndMonth;
    private javax.swing.JTextField fieldEndYear;
    private javax.swing.JTextField fieldStartDay;
    private javax.swing.JTextField fieldStartMonth;
    private javax.swing.JTextField fieldStartYear;
    private javax.swing.JLabel labelFromDate;
    private javax.swing.JLabel labelToTheDate;
    private javax.swing.JLabel monthFromLabel;
    private javax.swing.JLabel monthOfEndingLabel;
    private javax.swing.JPanel panelGetCars;
    private javax.swing.JPanel servicePanel;
    private javax.swing.JLabel yearOfPurchaseLabel;
    private javax.swing.JLabel yearOfPurchaseLabel1;
    // End of variables declaration//GEN-END:variables
}
