USE SecondhandCars
GO
CREATE TABLE Customers(
	CustomerID INTEGER NOT NULL IDENTITY PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	PhoneNumber VARCHAR(50) NOT NULL,
	Address VARCHAR(50),
	Email VARCHAR(50))
CREATE TABLE TransactionOrder(
	TransactionOrderID INTEGER NOT NULL IDENTITY PRIMARY KEY,
	CustomerID INTEGER FOREIGN KEY REFERENCES Customers(CustomerID),
	Type VARCHAR(50) NOT NULL,
	Amount MONEY NOT NULL)
CREATE TABLE CarSale(
	CarSaleID INTEGER NOT NULL IDENTITY PRIMARY KEY REFERENCES TransactionOrder(TransactionOrderID),
	CarID INTEGER NOT NULL FOREIGN KEY REFERENCES CarStock(CarID),
	SaleDate DATE NOT NULL)
CREATE TABLE TireService(
	TireServiceID INTEGER NOT NULL IDENTITY PRIMARY KEY REFERENCES TransactionOrder(TransactionOrderID),
	ServiceDate DATE NOT NULL,
	Description VARCHAR(500),
	Hours DECIMAL NOT NULL)
CREATE TABLE ChipTuning(
	ChipTuningID INTEGER NOT NULL IDENTITY PRIMARY KEY REFERENCES TransactionOrder(TransactionOrderID),
	TuningDate DATE NOT NULL,
	Description VARCHAR(500),
	Hours DECIMAL NOT NULL)
CREATE TABLE TireHotel(
	TireSetID INTEGER NOT NULL IDENTITY PRIMARY KEY,
	Location VARCHAR(50) NOT NULL,
	Description VARCHAR(500),
	Amount INTEGER NOT NULL)
CREATE TABLE TireVacation(
	TireVacationID INTEGER NOT NULL IDENTITY PRIMARY KEY REFERENCES TransactionOrder(TransactionOrderID),
	TireSetID INTEGER NOT NULL FOREIGN KEY REFERENCES TireHotel(TireSetID),
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL)
CREATE TABLE Repair(
	RepairID INTEGER NOT NULL IDENTITY PRIMARY KEY REFERENCES TransactionOrder(TransactionOrderID),
	Type VARCHAR(50) NOT NULL,
	RepairDate DATE NOT NULL,
	Hours DECIMAL NOT NULL,
	Description VARCHAR(500))